//
// Created by JPDSP on 29/08/2017.
//

#ifndef REWRITE_MOBILEED_DATA_VSTORE_H
#define REWRITE_MOBILEED_DATA_VSTORE_H

#define VSTORE_NAME "LojaED"
#define VSTORE_ARRAY_ITEMMAX 20

#endif //REWRITE_MOBILEED_DATA_VSTORE_H
